  info:
  - name: Application Namespace
    value: spinnaker
  selector:
    matchLabels:
      app.kubernetes.io/name: $DEPLOYMENT_NAME
  componentKinds:
  - group: v1
    kind: ConfigMap
  - group: extensions/v1beta1
    kind: Deployment
  - group: v1
    kind: PersistentVolumeClaim
  - group: v1
    kind: Secret
  - group: v1
    kind: Service
  - group: apps/v1beta2
    kind: StatefulSet
